### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by obv-mikhail** [meh/rust-uinput-sys#1]
```
error: no matching package named `ioctl` found (required by `uinput-sys`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.3
```

**Comment by obv-mikhail** [comment]
Use [nix](https://github.com/nix-rust/nix) maybe?

**Comment by meh** [comment]
I wanted to avoid the entirety of `nix` for just a couple ioctls.

**Comment by dpelevin** [comment]
@meh, in the case you want to avoid the usage of 'nix' crate, may be you can accept my pull request #2 just as a temporary solution to have crate release which can be built, till you roll out the final solution which is suitable from you point of view?

**Comment by meh** [comment]
It's building locally now, reopen if it fails.
